language: python
dist: xenial
python:
    - "3.7.3"

install:
    - pip install -r requirements.txt

script:
    - pip install -e .
    - pytest tests/
    
notifications:
    email:
        recipients:
            - johnwlambert@gmail.com
        on_success: change
        on_failure: change
