name: Python CI

# Run this workflow every time a new commit is pushed to repository
on: [pull_request]

jobs:
  run-unit-tests:
    
    name: Run all unit tests in codebase
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Test with pytest
      run: |
        pip install -e .
        pip install pytest
        pytest tests/

    - name: Flake check
      run: |
        pip install flake8
        flake8 --max-line-length 120 --ignore E201,E202,E203,E231,W291,W293,E303,W391,E402,W503,E731 waymo2argo
